---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:jdavis10213/podinfo
    path: charts/podinfo
    ref: master
  values:
    image: jdavis10213/podinfo:dev-gy4pl8if
    replicaCount: 1
    hpa:
      enabled: false
