---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-stage
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:stg-*
spec:
  releaseName: podinfo-stage
  chart:
    git: git@github.com:jdavis10213/podinfo
    path: charts/podinfo
    ref: master
  values:
    image: jdavis10213/podinfo:stg-t7i4phdx
    replicaCount: 2
    hpa:
      enabled: false
